### ISSUE TITLE
'Generate records' form is not displaying complete view.

### ISSUE THREAD

**Issue by guptas-sugarcrm** [sugarcrm/SidecarDevTools#23]
**SUMMARY**
_'Generate records'_ form is not displaying complete view.

**ENVIRONMENT**
- Sidecar Debugger Tool - 0.1
- Google Chrome - 45

**STEPS TO REPRODUCE**
1. Navigates to 'Sidecar Debugger Tool' tab in the Chrome dev tool. _(should be in landscape view of the debugger)_
2. Go to 'Generate records' tab
3. Scroll down the view.

**EXPECTED RESULT**
3. The view should scroll down properly and should display complete view.

**ACTUAL RESULT**
3. The view does not scroll down completely and hence not displaying complete view.

**ATTACHED SCREENSHOTS**
1. bottomView.png
2. rightSideView.png

_**NOTE:** A complete debugger view appears when used on the right side of the screen._

<img width="1280" alt="bottomview" src="https://cloud.githubusercontent.com/assets/9282163/9884732/01664746-5bff-11e5-8b22-7b55ddd0f446.png">
<img width="1214" alt="rightsideview" src="https://cloud.githubusercontent.com/assets/9282163/9884733/016cf7e4-5bff-11e5-8604-0b46acff6a8d.png">

**Comment by mmarum-sugarcrm** [comment]
Should be fixed now.
